version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - repository-dispatch
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
