name: 'Repository Dispatch'
description: 'Sends a repository dispatch event'
inputs:
  event-type:
    description: 'The event type to send'
    required: true
    default: 'custom-event'
  payload:
    description: 'The payload to send'
    required: false
  repository:
    description: 'The repository to send the event to (defaults to the current repository)'
    required: false
    default: ${{ github.repository }}
runs:
  using: "composite"
  steps:
    - name: Send repository dispatch event
      uses: actions/github-script@v8
      env:
        EVENT_TYPE: ${{ inputs.event-type }}
        PAYLOAD: ${{ inputs.payload }}
        REPOSITORY: ${{ inputs.repository }}
      with:
        script: |
          const eventType = process.env.EVENT_TYPE;
          const payload = process.env.PAYLOAD;

          const repository = process.env.REPOSITORY;

          const payload = payload ? JSON.parse(payload) : undefined;

          await github.rest.repos.createDispatchEvent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            event_type: eventType,
            client_payload: payload
          });