name: 'Receive Event'
description: 'Receives a custom event from a repository'
inputs:
  event-type:
    description: 'The event type to receive'
    required: true
    default: 'custom-event'
runs:
  using: "composite"
  steps:
    - name: Install ajv-cli
      shell: bash
      run: | 
        # Install ajv-cli for JSON schema validation
        npm install ajv-cli

    - name: Create event file
      shell: bash
      id: event-file
      run: |
        # Create a file to hold the event payload
        TEMP_FILE=$(mktemp /tmp/event-XXXXXX.json)
        echo "$PAYLOAD" > "$TEMP_FILE"
        echo "file=$TEMP_FILE" >> $GITHUB_OUTPUT
      env:
        PAYLOAD: ${{ toJson(github.event.client_payload) }}

    - name: Create payload file
      shell: bash
      id: payload-file
      run: |
        # Create a file to hold the payload extracted from the event
        TEMP_FILE=$(mktemp /tmp/payload-XXXXXX.json)
        jq '.payload' "$PAYLOAD_FILE" > "$TEMP_FILE"
        echo "file=$TEMP_FILE" >> $GITHUB_OUTPUT
      env:
        PAYLOAD_FILE: ${{ steps.payload-file.outputs.file }}

    - name: Validate payload
      shell: bash
      run: |
        # Validate the payload against the schema for the given event type
        npx ajv-cli validate -s "$SCHEMA" -d "$PAYLOAD_FILE"
      env:
        SCHEMA: ${{ github.action_path }}/schema/${{ inputs.event-type }}.json
        PAYLOAD_FILE: ${{ steps.payload-file.outputs.file }}